# Generated by Django 5.2.4 on 2026-05-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=500)),
                ('variant', models.CharField(blank=True, max_length=200, null=True)),
                ('perfume_type', models.CharField(default='Unknown', max_length=50)),
                ('gender', models.CharField(default='Unknown', max_length=20)),
                ('ml', models.IntegerField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_price', models.IntegerField(blank=True, null=True)),
                ('original_price', models.IntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('source_site', models.CharField(max_length=200)),
                ('source_url', models.URLField(max_length=500)),
                ('scraped_at', models.DateField()),
            ],
            options={
                'ordering': ['brand', 'product_name'],
                'unique_together': {('sku', 'source_site')},
            },
        ),
    ]
