# Generated by Django 5.2.4 on 2026-06-11 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('base_url', models.URLField(max_length=500)),
                ('engine_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500)),
                ('sale_price', models.IntegerField(blank=True, null=True)),
                ('original_price', models.IntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('current_hash', models.CharField(blank=True, max_length=64)),
                ('scraped_at', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='catalog.product')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='catalog.source')),
            ],
            options={
                'unique_together': {('product', 'source')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.IntegerField(blank=True, null=True)),
                ('original_price', models.IntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.productlisting')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
